jhipster-prod-postgresql:
  container_name: HealthPlanPicker-prod-postgresql
  image: postgres:9.4.5
  # volumes:
  # - ~/volumes/jhipster/HealthPlanPicker/prod-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=HealthPlanPicker
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

